"""created  PVPANEL table 

Revision ID: 296752747724
Revises: 9d8f64891e1a
Create Date: 2024-04-30 17:15:17.523219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '296752747724'
down_revision: Union[str, None] = '9d8f64891e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('cell_technology', sa.String(length=20), nullable=False),
    sa.Column('dimensions', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('maximum_power', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('open_circuit_voltage', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('short_circuit_current', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('maximum_power_voltage', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('maximum_power_current', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('module_efficiency', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('maximum_system_voltage', sa.Integer(), nullable=False),
    sa.Column('power_temp_coefficient', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('voltage_temp_coefficient', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('current_temp_coefficient', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('operating_temp_range', sa.String(length=20), nullable=False),
    sa.Column('maximum_wind_load', sa.Integer(), nullable=False),
    sa.Column('maximum_snow_load', sa.Integer(), nullable=False),
    sa.Column('junction_box', sa.String(length=20), nullable=False),
    sa.Column('connector', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panel')
    # ### end Alembic commands ###
