"""Update PVPANEL table 

Revision ID: 2c6c25f768a1
Revises: 37fa9a3136aa
Create Date: 2024-04-30 17:18:51.466015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6c25f768a1'
down_revision: Union[str, None] = '37fa9a3136aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('panel', 'model',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('panel', 'cell_technology',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('panel', 'dimensions',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('panel', 'weight',
               existing_type=sa.NUMERIC(precision=5, scale=1),
               nullable=True)
    op.alter_column('panel', 'maximum_power',
               existing_type=sa.NUMERIC(precision=5, scale=1),
               nullable=True)
    op.alter_column('panel', 'open_circuit_voltage',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               nullable=True)
    op.alter_column('panel', 'short_circuit_current',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('panel', 'maximum_power_voltage',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               nullable=True)
    op.alter_column('panel', 'maximum_power_current',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('panel', 'module_efficiency',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               nullable=True)
    op.alter_column('panel', 'maximum_system_voltage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('panel', 'power_temp_coefficient',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=True)
    op.alter_column('panel', 'voltage_temp_coefficient',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=True)
    op.alter_column('panel', 'current_temp_coefficient',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               nullable=True)
    op.alter_column('panel', 'operating_temp_range',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('panel', 'maximum_wind_load',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('panel', 'maximum_snow_load',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('panel', 'junction_box',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('panel', 'connector',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('panel', 'connector',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('panel', 'junction_box',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('panel', 'maximum_snow_load',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('panel', 'maximum_wind_load',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('panel', 'operating_temp_range',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('panel', 'current_temp_coefficient',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               nullable=False)
    op.alter_column('panel', 'voltage_temp_coefficient',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=False)
    op.alter_column('panel', 'power_temp_coefficient',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=False)
    op.alter_column('panel', 'maximum_system_voltage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('panel', 'module_efficiency',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               nullable=False)
    op.alter_column('panel', 'maximum_power_current',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('panel', 'maximum_power_voltage',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               nullable=False)
    op.alter_column('panel', 'short_circuit_current',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('panel', 'open_circuit_voltage',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               nullable=False)
    op.alter_column('panel', 'maximum_power',
               existing_type=sa.NUMERIC(precision=5, scale=1),
               nullable=False)
    op.alter_column('panel', 'weight',
               existing_type=sa.NUMERIC(precision=5, scale=1),
               nullable=False)
    op.alter_column('panel', 'dimensions',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('panel', 'cell_technology',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('panel', 'model',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
