"""add one to many relationship to user and support ticket 

Revision ID: 318dadc8cde7
Revises: 2c6c25f768a1
Create Date: 2024-05-05 14:57:56.241005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '318dadc8cde7'
down_revision: Union[str, None] = '2c6c25f768a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_ticket', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'support_ticket', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'support_ticket', type_='foreignkey')
    op.drop_column('support_ticket', 'user_id')
    # ### end Alembic commands ###
