"""added auto-increment to ID of PVPANEL 

Revision ID: 38124415a5d4
Revises: 9275a0ceeff4
Create Date: 2024-04-29 22:50:33.837675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38124415a5d4'
down_revision: Union[str, None] = '9275a0ceeff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
