"""Update PVPANEL table 

Revision ID: 3bcf5070ab4d
Revises: 1f9d8ec5ffba
Create Date: 2024-04-30 17:11:38.791375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bcf5070ab4d'
down_revision: Union[str, None] = '1f9d8ec5ffba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panel', sa.Column('maximum_power', sa.Numeric(precision=5, scale=1), nullable=False))
    op.add_column('panel', sa.Column('maximum_power_voltage', sa.Numeric(precision=4, scale=1), nullable=False))
    op.add_column('panel', sa.Column('maximum_power_current', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('panel', sa.Column('maximum_system_voltage', sa.Integer(), nullable=False))
    op.add_column('panel', sa.Column('power_temp_coefficient', sa.Numeric(precision=4, scale=2), nullable=False))
    op.add_column('panel', sa.Column('voltage_temp_coefficient', sa.Numeric(precision=4, scale=2), nullable=False))
    op.add_column('panel', sa.Column('current_temp_coefficient', sa.Numeric(precision=5, scale=3), nullable=False))
    op.add_column('panel', sa.Column('maximum_wind_load', sa.Integer(), nullable=False))
    op.add_column('panel', sa.Column('maximum_snow_load', sa.Integer(), nullable=False))
    op.alter_column('panel', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('panel', 'cell_technology',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('panel', 'dimensions',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('panel', 'weight',
               existing_type=sa.TEXT(),
               type_=sa.Numeric(precision=5, scale=1),
               nullable=False)
    op.alter_column('panel', 'open_circuit_voltage',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=4, scale=1),
               nullable=False)
    op.alter_column('panel', 'short_circuit_current',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               nullable=False)
    op.alter_column('panel', 'module_efficiency',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=4, scale=1),
               nullable=False)
    op.alter_column('panel', 'operating_temp_range',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('panel', 'junction_box',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('panel', 'connector',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.drop_column('panel', 'max_power_current')
    op.drop_column('panel', 'max_power_stc')
    op.drop_column('panel', 'power_temp_coeff')
    op.drop_column('panel', 'power_output_warranty')
    op.drop_column('panel', 'power_output')
    op.drop_column('panel', 'max_power_voltage')
    op.drop_column('panel', 'current_temp_coeff')
    op.drop_column('panel', 'max_snow_load')
    op.drop_column('panel', 'max_wind_load')
    op.drop_column('panel', 'efficiency')
    op.drop_column('panel', 'voltage_temp_coeff')
    op.drop_column('panel', 'product_warranty')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panel', sa.Column('product_warranty', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('panel', sa.Column('voltage_temp_coeff', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('panel', sa.Column('efficiency', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('panel', sa.Column('max_wind_load', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('panel', sa.Column('max_snow_load', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('panel', sa.Column('current_temp_coeff', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('panel', sa.Column('max_power_voltage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('panel', sa.Column('power_output', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('panel', sa.Column('power_output_warranty', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('panel', sa.Column('power_temp_coeff', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('panel', sa.Column('max_power_stc', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('panel', sa.Column('max_power_current', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('panel', 'connector',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panel', 'junction_box',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panel', 'operating_temp_range',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panel', 'module_efficiency',
               existing_type=sa.Numeric(precision=4, scale=1),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('panel', 'short_circuit_current',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('panel', 'open_circuit_voltage',
               existing_type=sa.Numeric(precision=4, scale=1),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('panel', 'weight',
               existing_type=sa.Numeric(precision=5, scale=1),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panel', 'dimensions',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panel', 'cell_technology',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panel', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('panel', 'maximum_snow_load')
    op.drop_column('panel', 'maximum_wind_load')
    op.drop_column('panel', 'current_temp_coefficient')
    op.drop_column('panel', 'voltage_temp_coefficient')
    op.drop_column('panel', 'power_temp_coefficient')
    op.drop_column('panel', 'maximum_system_voltage')
    op.drop_column('panel', 'maximum_power_current')
    op.drop_column('panel', 'maximum_power_voltage')
    op.drop_column('panel', 'maximum_power')
    # ### end Alembic commands ###
