"""update sender column to SupportTicketMessage 

Revision ID: 5c812017f5bf
Revises: ff11973f2cae
Create Date: 2024-05-05 22:50:31.606960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c812017f5bf'
down_revision: Union[str, None] = 'ff11973f2cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('support_ticket_message_support_ticket_id_fkey', 'support_ticket_message', type_='foreignkey')
    op.create_foreign_key(None, 'support_ticket_message', 'users', ['support_ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_column('support_ticket_message', 'sender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_ticket_message', sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'support_ticket_message', type_='foreignkey')
    op.create_foreign_key('support_ticket_message_support_ticket_id_fkey', 'support_ticket_message', 'support_ticket', ['support_ticket_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
