"""change foreign key of SupportTicketMessage

Revision ID: 9895a2b1836e
Revises: 5f6d34716e2f
Create Date: 2024-05-07 13:05:36.838629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9895a2b1836e'
down_revision: Union[str, None] = '5f6d34716e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_ticket_message', sa.Column('user_email', sa.String(), nullable=False))
    op.drop_constraint('support_ticket_message_user_id_fkey', 'support_ticket_message', type_='foreignkey')
    op.create_foreign_key(None, 'support_ticket_message', 'users', ['user_email'], ['email'], ondelete='CASCADE')
    op.drop_column('support_ticket_message', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_ticket_message', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'support_ticket_message', type_='foreignkey')
    op.create_foreign_key('support_ticket_message_user_id_fkey', 'support_ticket_message', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('support_ticket_message', 'user_email')
    # ### end Alembic commands ###
