"""update panel table

Revision ID: 9d29e350cf01
Revises: 5a24b904ae5d
Create Date: 2024-04-29 22:36:30.040655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d29e350cf01'
down_revision: Union[str, None] = '5a24b904ae5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pv_panel', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('pv_panel', sa.Column('model', sa.String(length=50), nullable=True))
    op.add_column('pv_panel', sa.Column('cell_technology', sa.String(length=50), nullable=True))
    op.add_column('pv_panel', sa.Column('dimensions', sa.String(length=50), nullable=True))
    op.add_column('pv_panel', sa.Column('weight', sa.String(length=20), nullable=True))
    op.add_column('pv_panel', sa.Column('product_warranty', sa.String(length=50), nullable=True))
    op.add_column('pv_panel', sa.Column('power_output_warranty', sa.String(length=50), nullable=True))
    op.add_column('pv_panel', sa.Column('max_power_stc', sa.Integer(), nullable=True))
    op.add_column('pv_panel', sa.Column('open_circuit_voltage', sa.DECIMAL(precision=4, scale=2), nullable=True))
    op.add_column('pv_panel', sa.Column('short_circuit_current', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('pv_panel', sa.Column('max_power_voltage', sa.DECIMAL(precision=4, scale=2), nullable=True))
    op.add_column('pv_panel', sa.Column('max_power_current', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('pv_panel', sa.Column('module_efficiency', sa.DECIMAL(precision=4, scale=1), nullable=True))
    op.add_column('pv_panel', sa.Column('power_temp_coeff', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('pv_panel', sa.Column('voltage_temp_coeff', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('pv_panel', sa.Column('current_temp_coeff', sa.DECIMAL(precision=5, scale=3), nullable=True))
    op.add_column('pv_panel', sa.Column('operating_temp_range', sa.String(length=20), nullable=True))
    op.add_column('pv_panel', sa.Column('max_wind_load', sa.Integer(), nullable=True))
    op.add_column('pv_panel', sa.Column('max_snow_load', sa.Integer(), nullable=True))
    op.add_column('pv_panel', sa.Column('junction_box', sa.String(length=20), nullable=True))
    op.add_column('pv_panel', sa.Column('connector', sa.String(length=20), nullable=True))
    op.drop_column('pv_panel', 'price')
    op.drop_column('pv_panel', 'capacity')
    op.drop_column('pv_panel', 'model_name')
    op.drop_column('pv_panel', 'efficiency')
    op.drop_column('pv_panel', 'panel_id')
    op.drop_column('pv_panel', 'manufacturer')
    op.drop_column('pv_panel', 'manufacture_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pv_panel', sa.Column('manufacture_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('pv_panel', sa.Column('manufacturer', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pv_panel', sa.Column('panel_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('pv_panel', sa.Column('efficiency', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pv_panel', sa.Column('model_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('pv_panel', sa.Column('capacity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('pv_panel', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('pv_panel', 'connector')
    op.drop_column('pv_panel', 'junction_box')
    op.drop_column('pv_panel', 'max_snow_load')
    op.drop_column('pv_panel', 'max_wind_load')
    op.drop_column('pv_panel', 'operating_temp_range')
    op.drop_column('pv_panel', 'current_temp_coeff')
    op.drop_column('pv_panel', 'voltage_temp_coeff')
    op.drop_column('pv_panel', 'power_temp_coeff')
    op.drop_column('pv_panel', 'module_efficiency')
    op.drop_column('pv_panel', 'max_power_current')
    op.drop_column('pv_panel', 'max_power_voltage')
    op.drop_column('pv_panel', 'short_circuit_current')
    op.drop_column('pv_panel', 'open_circuit_voltage')
    op.drop_column('pv_panel', 'max_power_stc')
    op.drop_column('pv_panel', 'power_output_warranty')
    op.drop_column('pv_panel', 'product_warranty')
    op.drop_column('pv_panel', 'weight')
    op.drop_column('pv_panel', 'dimensions')
    op.drop_column('pv_panel', 'cell_technology')
    op.drop_column('pv_panel', 'model')
    op.drop_column('pv_panel', 'id')
    # ### end Alembic commands ###
