"""droped PVPANEL table 

Revision ID: 9d8f64891e1a
Revises: 3bcf5070ab4d
Create Date: 2024-04-30 17:14:52.613974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d8f64891e1a'
down_revision: Union[str, None] = '3bcf5070ab4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panel',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cell_technology', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dimensions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_warranty', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('power_output_warranty', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_power_stc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('open_circuit_voltage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('short_circuit_current', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_power_voltage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_power_current', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('module_efficiency', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('power_temp_coeff', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('voltage_temp_coeff', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_temp_coeff', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('operating_temp_range', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_wind_load', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_snow_load', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('junction_box', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('connector', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('power_output', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('efficiency', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='panel_pkey')
    )
    # ### end Alembic commands ###
