"""Update PVPANEL id 

Revision ID: e32d4e437f9d
Revises: 22e09e3a4ae6
Create Date: 2024-04-29 22:54:24.452158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32d4e437f9d'
down_revision: Union[str, None] = '22e09e3a4ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('cell_technology', sa.Text(), nullable=True),
    sa.Column('dimensions', sa.Text(), nullable=True),
    sa.Column('weight', sa.Text(), nullable=True),
    sa.Column('product_warranty', sa.Text(), nullable=True),
    sa.Column('power_output_warranty', sa.Text(), nullable=True),
    sa.Column('max_power_stc', sa.Integer(), nullable=True),
    sa.Column('open_circuit_voltage', sa.Integer(), nullable=True),
    sa.Column('short_circuit_current', sa.Integer(), nullable=True),
    sa.Column('max_power_voltage', sa.Integer(), nullable=True),
    sa.Column('max_power_current', sa.Integer(), nullable=True),
    sa.Column('module_efficiency', sa.Integer(), nullable=True),
    sa.Column('power_temp_coeff', sa.Integer(), nullable=True),
    sa.Column('voltage_temp_coeff', sa.Integer(), nullable=True),
    sa.Column('current_temp_coeff', sa.Integer(), nullable=True),
    sa.Column('operating_temp_range', sa.Text(), nullable=True),
    sa.Column('max_wind_load', sa.Integer(), nullable=True),
    sa.Column('max_snow_load', sa.Integer(), nullable=True),
    sa.Column('junction_box', sa.Text(), nullable=True),
    sa.Column('connector', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panel')
    # ### end Alembic commands ###
