"""update devices table

Revision ID: fdb5905e706e
Revises: bf034eed1b42
Create Date: 2024-04-02 02:09:17.924754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb5905e706e'
down_revision: Union[str, None] = 'bf034eed1b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('consumption_watt', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('average_daily_usage_hour', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('devices', sa.Column('standby_power_consumption', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('standby_duration_hours', sa.Integer(), nullable=True))
    op.drop_column('devices', 'power_rating')
    op.drop_column('devices', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('power_rating', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('devices', 'standby_duration_hours')
    op.drop_column('devices', 'standby_power_consumption')
    op.drop_column('devices', 'average_daily_usage_hour')
    op.drop_column('devices', 'consumption_watt')
    # ### end Alembic commands ###
