"""added a sender column to SupportTicketMessage 

Revision ID: ff11973f2cae
Revises: 318dadc8cde7
Create Date: 2024-05-05 22:25:05.276476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff11973f2cae'
down_revision: Union[str, None] = '318dadc8cde7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_ticket_message', sa.Column('sender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_ticket_message', 'sender')
    # ### end Alembic commands ###
