from sqlalchemy.orm import Session
from app.config.database import get_db
from app.entity.models import User

"""
WARNING: Running this script multiple times will generate duplicate data and may throw unique constraint exceptions.
Only execute this script if you want to insert the provided data into the database once.

"""

file = [
    {
        "first_name": "Milka",
        "last_name": "Bilt",
        "phone": "243-990-1492",
        "email": "mbilt0@wsj.com",
        "nationality": "China",
        "password": "zF8_m9drYZG`6Q",
        "country": "United States",
        "street": "09547 South Street",
        "city": "Leping",
        "state": None,
        "postal_code": None,
    },
    {
        "first_name": "Graeme",
        "last_name": "Boord",
        "phone": "161-933-0944",
        "email": "gboord1@java.com",
        "nationality": "Philippines",
        "password": "mE1*1uQ!",
        "country": "China",
        "street": "81 Main Trail",
        "city": "Maguyam",
        "state": None,
        "postal_code": "9400",
    },
    {
        "first_name": "Sileas",
        "last_name": "Maylor",
        "phone": "280-458-7080",
        "email": "smaylor2@google.ru",
        "nationality": "Belize",
        "password": "lR4'\\&?t>4&~K7s",
        "country": "Cape Verde",
        "street": "70 Loeprich Street",
        "city": "Belize City",
        "state": None,
        "postal_code": None,
    },
    {
        "first_name": "Lynnette",
        "last_name": "Crennell",
        "phone": "213-658-0687",
        "email": "lcrennell3@vkontakte.ru",
        "nationality": "United States",
        "password": "kH5|<0P\\b'LfYm!",
        "country": "Indonesia",
        "street": "536 Shoshone Point",
        "city": "Los Angeles",
        "state": "California",
        "postal_code": "90045",
    },
    {
        "first_name": "Tedmund",
        "last_name": "Rosenhaus",
        "phone": "643-124-3797",
        "email": "trosenhaus4@shareasale.com",
        "nationality": "Czech Republic",
        "password": "hR3`!I4OF",
        "country": "Mongolia",
        "street": "4786 Eggendart Road",
        "city": "Malé Svatoňovice",
        "state": None,
        "postal_code": "542 34",
    },
    {
        "first_name": "Abel",
        "last_name": "Batchelar",
        "phone": "434-954-6001",
        "email": "abatchelar5@cam.ac.uk",
        "nationality": "Egypt",
        "password": "bS2!z#LiALf",
        "country": "Russia",
        "street": "72291 Armistice Hill",
        "city": "Ţāmiyah",
        "state": None,
        "postal_code": None,
    },
    {
        "first_name": "Winifield",
        "last_name": "Sandaver",
        "phone": "994-623-3637",
        "email": "wsandaver6@rediff.com",
        "nationality": "New Caledonia",
        "password": "rG3=y/*#Z8f#cvZb",
        "country": "Philippines",
        "street": "21 Pawling Drive",
        "city": "Koumac",
        "state": None,
        "postal_code": "98850",
    },
    {
        "first_name": "Taffy",
        "last_name": "Raddon",
        "phone": "232-358-0875",
        "email": "traddon7@linkedin.com",
        "nationality": "Mexico",
        "password": "uP6`A@A1e|QPrK3",
        "country": "China",
        "street": "096 Scoville Road",
        "city": "Lazaro Cardenas",
        "state": "Tabasco",
        "postal_code": "86723",
    },
    {
        "first_name": "Mikael",
        "last_name": "Badrick",
        "phone": "511-754-1099",
        "email": "mbadrick8@webmd.com",
        "nationality": "China",
        "password": "vO5,PTD*kCU",
        "country": "Bahrain",
        "street": "7 Bobwhite Junction",
        "city": "Baiyang",
        "state": None,
        "postal_code": None,
    },
    {
        "first_name": "Killy",
        "last_name": "Stolli",
        "phone": "711-276-7245",
        "email": "kstolli9@ed.gov",
        "nationality": "Brazil",
        "password": 'eP4"!/Vy}=f',
        "country": "Serbia",
        "street": "1249 Northview Junction",
        "city": "Itinga",
        "state": None,
        "postal_code": "39610-000",
    },
    {
        "first_name": "Regine",
        "last_name": "Pinckney",
        "phone": "597-925-0163",
        "email": "rpinckneya@oracle.com",
        "nationality": "Russia",
        "password": "tS2%S'u`/A",
        "country": "China",
        "street": "56 Chive Trail",
        "city": "Shakhty",
        "state": None,
        "postal_code": "346530",
    },
    {
        "first_name": "Christophe",
        "last_name": "Pycock",
        "phone": "120-650-5928",
        "email": "cpycockb@senate.gov",
        "nationality": "Indonesia",
        "password": "kK8?/hjR4\\&",
        "country": "Indonesia",
        "street": "48175 Pierstorff Avenue",
        "city": "Ketara",
        "state": None,
        "postal_code": None,
    },
    {
        "first_name": "Pansy",
        "last_name": "Hindhaugh",
        "phone": "114-965-8501",
        "email": "phindhaughc@state.tx.us",
        "nationality": "Slovenia",
        "password": "dQ0%{*.R",
        "country": "Indonesia",
        "street": "02004 Wayridge Terrace",
        "city": "Lucija",
        "state": None,
        "postal_code": "6333",
    },
    {
        "first_name": "D'arcy",
        "last_name": "Reede",
        "phone": "620-494-9637",
        "email": "dreeded@scribd.com",
        "nationality": "Indonesia",
        "password": "oM5=flV,jF",
        "country": "China",
        "street": "5570 Valley Edge Road",
        "city": "Riang Tengah",
        "state": None,
        "postal_code": None,
    },
    {
        "first_name": "Ursa",
        "last_name": "Haggith",
        "phone": "526-628-4286",
        "email": "uhaggithe@furl.net",
        "nationality": "Portugal",
        "password": "fX9>q=,@R)",
        "country": "Argentina",
        "street": "33412 Mcbride Avenue",
        "city": "Miraflores",
        "state": "Lisboa",
        "postal_code": "1495-048",
    },
]


def seed():
    db: Session = get_db()


    for data in file:
        db.add(User(**data))
    print("DONE")
    db.commit()


